version: "3"

volumes:
  nodejs_node_modules:
    driver: local

services:
  nodejs:
    build:
      context: "./"
      dockerfile: "docker/nodejs/Dockerfile"
    tty: true
    volumes:
      - ./:/app
      - nodejs_node_modules:/app/node_modules
    ports:
      - "8080:8080"
    command: bash /app/docker/nodejs/start_dev_server.sh
    working_dir: /app

